services:
  - type: web
    name: nutri-4-0-backend
    env: python
    region: oregon
    plan: free
    buildCommand: cd backend && pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd backend && python manage.py migrate && gunicorn setup.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120
    envVars:
      - key: PYTHON_PATH
        value: /opt/render/project/src/backend